version: "3.1"
services:
  client:
    image: jmuleiro/react-demo-app:latest
    build: .
    depends_on:
      - server
    networks:
      - frontend
    ports:
      - "80:3001"
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
  server:
    image: jmuleiro/express-demo-app:latest
    build: .
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "3000:3000"
volumes:
  db_data: {}
networks:
  frontend:

  backend:
